In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

from sklearn.preprocessing import RobustScaler , StandardScaler
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

from sklearn.model_selection import StratifiedKFold,RepeatedStratifiedKFold, RandomizedSearchCV,GridSearchCV, RepeatedKFold

from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier

from sklearn.metrics import (
    accuracy_score,
    f1_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
)
from scikitplot.metrics import plot_roc
from sklearn.metrics import roc_curve, auc, roc_auc_score

In [2]:
df_train_pure=pd.read_csv("../Dataset_prepared/Prepared_train.csv")
df_test_pure=pd.read_csv("../Dataset_prepared/Prepared_test.csv")


In [3]:
df_train_c = df_train_pure.copy()
df_test_c = df_test_pure.copy()


In [4]:
df_train_c.drop('actor',axis=1,inplace=True)
df_train_c.drop('filename',axis=1,inplace=True)
#df_train.drop('Unnamed: 0',axis=1,inplace=True)


df_test_c.drop('actor',axis=1,inplace=True)
df_test_c.drop('filename',axis=1,inplace=True)
#df_test.drop('Unnamed: 0',axis=1,inplace=True)






In [5]:
indexNames = df_train_pure[ df_train_pure['emotional_intensity'] == 'strong' ].sample(frac=0.93).index
df_train_c.drop(indexNames,axis=0,inplace=True)



In [6]:
cat_var=["statement","repetition","sex","emotional_intensity","vocal_channel"]
le=preprocessing.LabelEncoder()
for i in cat_var:
    df_train_c[i]=le.fit_transform(df_train_c[i])
categorical_col = ["emotion"]

df_train_c = pd.get_dummies(df_train_c, columns=categorical_col)    

df_train_c.head()

vocal_channel  emotional_intensity  statement  repetition  sex  \
0              1                    0          1           0    1   
1              1                    0          1           1    1   
2              1                    0          0           0    1   
3              1                    0          0           1    1   
4              1                    0          1           0    1   

           mean       q25  q50  q75        kur  ...  stft_kur_w4  \
0  9.150000e-07 -0.000031  0.0  0.0  15.028520  ...     6.742190   
1  7.137790e-07 -0.000031  0.0  0.0  16.488415  ...    -0.700420   
2  9.554485e-07  0.000000  0.0  0.0  17.035218  ...     1.688986   
3  9.176213e-07 -0.000031  0.0  0.0  21.824521  ...    -0.594111   
4  8.108948e-07 -0.000031  0.0  0.0  13.236022  ...     0.126535   

   stft_skew_w4  emotion_angry  emotion_calm  emotion_disgust  \
0     -1.706215              0             0                0   
1     -0.201495              0             0                0   
2     -1.024773              0             0                0   
3     -0.412871              0             0                0   
4     -0.620782              0             1                0   

   emotion_fearful  emotion_happy  emotion_neutral  emotion_sad  \
0                0              0                1            0   
1                0              0                1            0   
2                0              0                1            0   
3                0              0                1            0   
4                0              0                0            0   

   emotion_surprised  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 266 columns]

In [7]:
numeric_features = [n for n in df_train_c.columns if n!="emotion_angry" and n!= "vocal_channel" and n!= "emotional_intensity" and n!= "statement" and n!= "repetition" and n!= "sex" and   n!="emotion_calm" and  n!="emotion_disgust" and  n!="emotion_fearful" and  n!="emotion_happy" and  n!="emotion_neutral" and n!="emotion_sad" and  n!="emotion_surprised"]

scaler = StandardScaler()
scaled_features = scaler.fit_transform(df_train_c[numeric_features])
df_train_c[numeric_features] = scaled_features
df_train_c.head()


col = [x for x in df_train_c.columns if x!='emotional_intensity']
X_train=df_train_c[col].values
y_train = np.array(df_train_c["emotional_intensity"])






In [8]:
for i in cat_var:
    df_test_c[i]=le.fit_transform(df_test_c[i])
categorical_col = ["emotion"]

df_test_c = pd.get_dummies(df_test_c, columns=categorical_col)    

df_test_c.head()

vocal_channel  emotional_intensity  statement  repetition  sex  \
0              1                    0          1           0    1   
1              1                    0          1           1    1   
2              1                    0          0           0    1   
3              1                    0          0           1    1   
4              1                    0          1           0    1   

           mean       q25  q50       q75        kur  ...  stft_kur_w4  \
0  2.940224e-06 -0.000092  0.0  0.000153  11.392131  ...    -0.260279   
1  7.733752e-07 -0.000122  0.0  0.000153  13.621589  ...    -0.428900   
2 -3.741909e-06 -0.000061  0.0  0.000092   7.678162  ...     0.626916   
3 -5.069646e-07 -0.000092  0.0  0.000122  14.511231  ...    -0.825144   
4  8.640319e-07 -0.000061  0.0  0.000122   8.944732  ...    -0.536669   

   stft_skew_w4  emotion_angry  emotion_calm  emotion_disgust  \
0     -0.566556              0             0                0   
1     -0.587210              0             0                0   
2     -0.883317              0             0                0   
3     -0.383701              0             0                0   
4     -0.547354              0             1                0   

   emotion_fearful  emotion_happy  emotion_neutral  emotion_sad  \
0                0              0                1            0   
1                0              0                1            0   
2                0              0                1            0   
3                0              0                1            0   
4                0              0                0            0   

   emotion_surprised  
0                  0  
1                  0  
2                  0  
3                  0  
4                  0  

[5 rows x 266 columns]

In [9]:
indexNames = df_test_c[ df_test_c['emotional_intensity'] == 'strong' ].sample(frac=0.93).index
df_test_c.drop(indexNames,axis=0,inplace=True)


In [10]:
numeric_features = [n for n in df_test_c.columns if n!="emotion_angry" and n!= "vocal_channel" and n!= "emotional_intensity" and n!= "statement" and n!= "repetition" and n!= "sex" and   n!="emotion_calm" and  n!="emotion_disgust" and  n!="emotion_fearful" and  n!="emotion_happy" and  n!="emotion_neutral" and n!="emotion_sad" and  n!="emotion_surprised"]


scaled_features = scaler.transform(df_test_c[numeric_features])
df_test_c[numeric_features] = scaled_features
df_test_c.head()


col = [x for x in df_test_c.columns if x!='emotional_intensity']
X_test=df_test_c[col].values
y_test = np.array(df_test_c["emotional_intensity"])






ADASYN + altre tecniche

In [11]:
from imblearn.under_sampling import RandomUnderSampler
from collections import Counter
from imblearn.over_sampling import SMOTE

In [12]:
ada = RandomUnderSampler(random_state=42)
X_res, y_res = ada.fit_resample(X_train, y_train)
print('Resampled dataset shape %s' % Counter(y_res))

Resampled dataset shape Counter({0: 59, 1: 59})


In [13]:
df = pd.DataFrame(X_res,columns=col)

In [14]:
df['emotional_intensity'] = y_res

In [15]:
df

vocal_channel  statement  repetition  sex      mean       q25       q50  \
0              0.0        1.0         1.0  1.0 -0.175150 -0.269601 -0.020881   
1              1.0        0.0         1.0  1.0 -0.027421  0.521551 -0.020881   
2              1.0        0.0         1.0  0.0  0.002715  0.543527 -0.020881   
3              0.0        1.0         0.0  0.0 -0.042893  0.367716 -0.020881   
4              0.0        0.0         1.0  1.0 -0.464303 -0.709130 -0.020881   
..             ...        ...         ...  ...       ...       ...       ...   
113            1.0        1.0         0.0  1.0 -0.900667  0.411669 -0.020881   
114            1.0        0.0         1.0  1.0  1.382520 -0.225648 -0.020881   
115            0.0        0.0         1.0  1.0 -1.973882 -4.071528  4.334794   
116            1.0        0.0         0.0  0.0 -0.009547  0.477598 -0.020881   
117            1.0        1.0         1.0  0.0 -0.048357  0.323763 -0.020881   

          q75       kur      skew  ...  stft_skew_w4  emotion_angry  \
0    0.888403 -0.428693  0.258919  ...     -0.088250            0.0   
1   -0.710697  0.129164 -0.554804  ...      0.320176            0.0   
2   -0.735298 -0.211978  0.726873  ...      0.199662            0.0   
3   -0.095658 -0.769759 -1.637050  ...     -0.260094            0.0   
4    1.786359 -0.771451  0.050328  ...     -0.048191            1.0   
..        ...       ...       ...  ...           ...            ...   
113 -0.513884  0.552691 -2.581698  ...      0.843949            0.0   
114  1.036012 -0.070807 -1.767740  ...     -1.828924            0.0   
115  4.923055 -0.206086  0.404534  ...     -1.086900            1.0   
116 -0.636892  0.082687  0.347012  ...      0.056690            1.0   
117 -0.415478  1.328307  0.666610  ...     -0.202103            0.0   

     emotion_calm  emotion_disgust  emotion_fearful  emotion_happy  \
0             0.0              0.0              1.0            0.0   
1             0.0              0.0              0.0            0.0   
2             0.0              0.0              0.0            0.0   
3             0.0              0.0              0.0            0.0   
4             0.0              0.0              0.0            0.0   
..            ...              ...              ...            ...   
113           0.0              0.0              0.0            1.0   
114           0.0              0.0              0.0            0.0   
115           0.0              0.0              0.0            0.0   
116           0.0              0.0              0.0            0.0   
117           0.0              0.0              1.0            0.0   

     emotion_neutral  emotion_sad  emotion_surprised  emotional_intensity  
0                0.0          0.0                0.0                    0  
1                1.0          0.0                0.0                    0  
2                1.0          0.0                0.0                    0  
3                0.0          1.0                0.0                    0  
4                0.0          0.0                0.0                    0  
..               ...          ...                ...                  ...  
113              0.0          0.0                0.0                    1  
114              0.0          0.0                1.0                    1  
115              0.0          0.0                0.0                    1  
116              0.0          0.0                0.0                    1  
117              0.0          0.0                0.0                    1  

[118 rows x 266 columns]

### Oultlier analysis

In [16]:
from sklearn.neighbors import LocalOutlierFactor
from sklearn.ensemble import IsolationForest
from pyod.models.abod import ABOD
from pyod.models.knn import KNN

In [17]:
clf_LOF = LocalOutlierFactor(n_neighbors = 21)
y_pred = clf_LOF.fit_predict(df)
y_outliers = df[y_pred==-1]
np.unique(y_pred, return_counts=True)

(array([-1,  1]), array([ 14, 104]))

In [18]:
# list with indexes and scores only for outliers --> np.where(y_pred==-1)
outlier_All_indexes_LOF = list(np.where(y_pred==-1)[0])
outlier_indexes = np.where(y_pred==-1)[0]
outlier_scores = clf_LOF.negative_outlier_factor_[outlier_indexes]

outlier_factor_list = []
for i in range(0,len(outlier_scores)):
    outlier_factor_list.append((outlier_indexes[i], outlier_scores[i]))
print(len(outlier_factor_list))

#We sort in ascending order with respect to LOF factor
def outlier_score(elem):
    return elem[1]
outlier_factor_list = sorted(outlier_factor_list, key=outlier_score)
outlier_factor_list[:10]

14


[(99, -2.1046731327675685),
 (85, -2.070196416543267),
 (68, -2.030976178953717),
 (67, -2.0046156409284692),
 (115, -1.9504829829174737),
 (86, -1.7700441502026512),
 (100, -1.6976449011592973),
 (46, -1.6539155101730092),
 (82, -1.6445721208071713),
 (116, -1.5934668840496484)]

###  knn

In [19]:
clf_KNN = KNN(n_neighbors=5)
clf_KNN.fit(df)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [20]:
outliers_KNN = clf_KNN.predict(df)
np.unique(outliers_KNN, return_counts=True)

(array([0, 1]), array([107,  11]))

In [21]:
outlier_All_indexes_knn=list(np.where(outliers_KNN==1)[0])
outlier_indexes_knn = np.where(outliers_KNN==1)[0]
outlier_scores_knn = clf_KNN.decision_scores_[outlier_indexes_knn]
y_outliers_knn = df[outliers_KNN==1]

### ABOD

In [22]:
clf_ABOD = ABOD()
clf_ABOD.fit(df)

ABOD(contamination=0.1, method='fast', n_neighbors=5)

In [23]:
outliers_ABOD = clf_ABOD.predict(df)
np.unique(outliers_ABOD, return_counts=True)

(array([0, 1]), array([106,  12]))

In [24]:
outlier_All_indexes_abod=list(np.where(outliers_ABOD==1)[0])
outlier_indexes_abod = np.where(outliers_ABOD==1)[0]
outlier_scores_abod = clf_ABOD.decision_scores_[outlier_indexes_abod]
y_outliers_ABOD = df[outliers_ABOD==1]

### ISO

In [25]:
from sklearn.ensemble import IsolationForest
clf_if = IsolationForest(random_state=0)
clf_if.fit(df)

IsolationForest(random_state=0)

In [26]:
outliers_if = clf_if.predict(df)
np.unique(outliers_if, return_counts=True)

(array([-1,  1]), array([  7, 111]))

In [27]:
outlier_All_indexes_IF=list(np.where(df == -1)[0])
y_outliers_if = df[outliers_if==1]
outlier_indexes_if = np.where(outliers_if == -1)[0]
indexes_list_if = list(outlier_indexes_if)  #retrieve index of outliers

outlier_scores_if=clf_if.decision_function(df)

### Intersezioni

INTERSEZIONE TECNICHE


In [28]:
set_LOF_ALL=set(outlier_All_indexes_LOF)
#set_HBOS_ALL=set(outlier_All_indexes_HBOS)
set_KNN_ALL=set(outlier_All_indexes_knn)
set_ABOD_ALL=set(outlier_All_indexes_abod)
#set_IF_ALL=set(outlier_All_indexes_IF)
intersection_Random = set.intersection(set_LOF_ALL,set_KNN_ALL,set_ABOD_ALL)
len(intersection_Random)

7

In [29]:
df.loc[intersection_Random]

vocal_channel  statement  repetition  sex       mean       q25       q50  \
67             1.0        0.0         0.0  1.0  -0.255898 -1.588189 -0.020881   
99             1.0        1.0         0.0  0.0   0.787946 -0.115766 -0.020881   
68             1.0        1.0         1.0  1.0   0.106668 -3.500140 -0.020881   
46             0.0        1.0         1.0  0.0   3.656416 -3.016658  8.690469   
82             1.0        1.0         1.0  0.0  -0.334822 -2.862823 -0.020881   
115            0.0        0.0         1.0  1.0  -1.973882 -4.071528  4.334794   
85             1.0        1.0         0.0  1.0 -14.355142 -1.588189 -8.732230   

          q75       kur      skew  ...  stft_skew_w4  emotion_angry  \
67   2.413698  1.065837  0.083170  ...     -1.359285            0.0   
99  -0.267869  1.419436  3.260225  ...     -2.198188            0.0   
68   4.283415  0.635975  0.113697  ...      2.276719            0.0   
46   2.118480 -0.750047  0.522037  ...     -1.770026            0.0   
82   1.847863 -0.460915  1.366414  ...      2.903386            0.0   
115  4.923055 -0.206086  0.404534  ...     -1.086900            1.0   
85   1.159020  3.611617  1.527304  ...     -2.211658            1.0   

     emotion_calm  emotion_disgust  emotion_fearful  emotion_happy  \
67            0.0              0.0              0.0            0.0   
99            0.0              0.0              0.0            1.0   
68            0.0              0.0              1.0            0.0   
46            0.0              0.0              1.0            0.0   
82            0.0              0.0              1.0            0.0   
115           0.0              0.0              0.0            0.0   
85            0.0              0.0              0.0            0.0   

     emotion_neutral  emotion_sad  emotion_surprised  emotional_intensity  
67               0.0          1.0                0.0                    1  
99               0.0          0.0                0.0                    1  
68               0.0          0.0                0.0                    1  
46               0.0          0.0                0.0                    0  
82               0.0          0.0                0.0                    1  
115              0.0          0.0                0.0                    1  
85               0.0          0.0                0.0                    1  

[7 rows x 266 columns]

In [30]:
intersection_normal = {
 249,
 292,
 308,
 309,
 311,
 382,
 554,
 832,
 1247,
 1283,
 1358,
 1481,
 1492,
 1702,
 1703,
 1704,
 1756,
 1757,
 1758,
 1801}

In [31]:
intersection_normal_Random = set.intersection(intersection_normal,intersection_Random)
len(intersection_normal_Random)

0

In [32]:
intersection_K = {40,
 352,
 425,
 546,
 840,
 853,
 954,
 970,
 971,
 1008,
 1015,
 1028,
 1029,
 1031,
 1360,
 1374,
 1703,
 1705}

In [33]:
intersection_K_Random = set.intersection(intersection_K,intersection_Random)
len(intersection_K_Random)

0

In [34]:
intersection_MDS = {352,546,1028,1029,1703,1031,40,425,1705,840,970,971,1360,1008,853,1015,954,1374}

In [35]:
intersection_MDS_Random = set.intersection(intersection_MDS,intersection_Random)
len(intersection_MDS_Random)

0

### OVERSAMPLING

In [36]:
from imblearn.over_sampling import SMOTE

In [39]:
sm = SMOTE(random_state=42)
X_res_a, y_res_a = sm.fit_resample(X_train, y_train)
print('Resampled dataset shape %s' % Counter(y_res_a))

Resampled dataset shape Counter({0: 984, 1: 984})


In [40]:
df1 = pd.DataFrame(X_res,columns=col)

In [41]:
df1['emotional_intensity'] = y_res

LOF

In [42]:
clf_LOF = LocalOutlierFactor(n_neighbors = 21)
y_pred = clf_LOF.fit_predict(df1)
y_outliers = df1[y_pred==-1]
np.unique(y_pred, return_counts=True)

(array([-1,  1]), array([ 14, 104]))

In [43]:
# list with indexes and scores only for outliers --> np.where(y_pred==-1)
outlier_All_indexes_LOF = list(np.where(y_pred==-1)[0])
outlier_indexes = np.where(y_pred==-1)[0]
outlier_scores = clf_LOF.negative_outlier_factor_[outlier_indexes]

outlier_factor_list = []
for i in range(0,len(outlier_scores)):
    outlier_factor_list.append((outlier_indexes[i], outlier_scores[i]))
print(len(outlier_factor_list))

#We sort in ascending order with respect to LOF factor
def outlier_score(elem):
    return elem[1]
outlier_factor_list = sorted(outlier_factor_list, key=outlier_score)
outlier_factor_list[:10]

14


[(99, -2.1046731327675685),
 (85, -2.070196416543267),
 (68, -2.030976178953717),
 (67, -2.0046156409284692),
 (115, -1.9504829829174737),
 (86, -1.7700441502026512),
 (100, -1.6976449011592973),
 (46, -1.6539155101730092),
 (82, -1.6445721208071713),
 (116, -1.5934668840496484)]

KNN

In [44]:
clf_KNN = KNN(n_neighbors=5)
clf_KNN.fit(df1)

KNN(algorithm='auto', contamination=0.1, leaf_size=30, method='largest',
  metric='minkowski', metric_params=None, n_jobs=1, n_neighbors=5, p=2,
  radius=1.0)

In [45]:
outliers_KNN = clf_KNN.predict(df1)
np.unique(outliers_KNN, return_counts=True)

(array([0, 1]), array([107,  11]))

In [46]:
outlier_All_indexes_knn=list(np.where(outliers_KNN==1)[0])
outlier_indexes_knn = np.where(outliers_KNN==1)[0]
outlier_scores_knn = clf_KNN.decision_scores_[outlier_indexes_knn]
y_outliers_knn = df1[outliers_KNN==1]

ABOD

In [47]:
clf_ABOD = ABOD()
clf_ABOD.fit(df1)

ABOD(contamination=0.1, method='fast', n_neighbors=5)

In [48]:
outliers_ABOD = clf_ABOD.predict(df1)
np.unique(outliers_ABOD, return_counts=True)

(array([0, 1]), array([106,  12]))

In [49]:
outlier_All_indexes_abod=list(np.where(outliers_ABOD==1)[0])
outlier_indexes_abod = np.where(outliers_ABOD==1)[0]
outlier_scores_abod = clf_ABOD.decision_scores_[outlier_indexes_abod]
y_outliers_ABOD = df1[outliers_ABOD==1]

ISO

In [51]:
clf_if = IsolationForest(random_state=0)
clf_if.fit(df1)

IsolationForest(random_state=0)

In [52]:
outlier_All_indexes_IF=list(np.where(df == -1)[0])
y_outliers_if = df1[outliers_if==1]
outlier_indexes_if = np.where(outliers_if == -1)[0]
indexes_list_if = list(outlier_indexes_if)  #retrieve index of outliers

outlier_scores_if=clf_if.decision_function(df1)

INTERSEZIONI

In [53]:
set_LOF_ALL=set(outlier_All_indexes_LOF)
#set_HBOS_ALL=set(outlier_All_indexes_HBOS)
set_KNN_ALL=set(outlier_All_indexes_knn)
set_ABOD_ALL=set(outlier_All_indexes_abod)
set_IF_ALL=set(outlier_All_indexes_IF)
intersection_Over = set.intersection(set_LOF_ALL,set_KNN_ALL,set_ABOD_ALL)
len(intersection_Over)

7

In [55]:
df1.loc[intersection_Over]

vocal_channel  statement  repetition  sex       mean       q25       q50  \
67             1.0        0.0         0.0  1.0  -0.255898 -1.588189 -0.020881   
99             1.0        1.0         0.0  0.0   0.787946 -0.115766 -0.020881   
68             1.0        1.0         1.0  1.0   0.106668 -3.500140 -0.020881   
46             0.0        1.0         1.0  0.0   3.656416 -3.016658  8.690469   
82             1.0        1.0         1.0  0.0  -0.334822 -2.862823 -0.020881   
115            0.0        0.0         1.0  1.0  -1.973882 -4.071528  4.334794   
85             1.0        1.0         0.0  1.0 -14.355142 -1.588189 -8.732230   

          q75       kur      skew  ...  stft_skew_w4  emotion_angry  \
67   2.413698  1.065837  0.083170  ...     -1.359285            0.0   
99  -0.267869  1.419436  3.260225  ...     -2.198188            0.0   
68   4.283415  0.635975  0.113697  ...      2.276719            0.0   
46   2.118480 -0.750047  0.522037  ...     -1.770026            0.0   
82   1.847863 -0.460915  1.366414  ...      2.903386            0.0   
115  4.923055 -0.206086  0.404534  ...     -1.086900            1.0   
85   1.159020  3.611617  1.527304  ...     -2.211658            1.0   

     emotion_calm  emotion_disgust  emotion_fearful  emotion_happy  \
67            0.0              0.0              0.0            0.0   
99            0.0              0.0              0.0            1.0   
68            0.0              0.0              1.0            0.0   
46            0.0              0.0              1.0            0.0   
82            0.0              0.0              1.0            0.0   
115           0.0              0.0              0.0            0.0   
85            0.0              0.0              0.0            0.0   

     emotion_neutral  emotion_sad  emotion_surprised  emotional_intensity  
67               0.0          1.0                0.0                    1  
99               0.0          0.0                0.0                    1  
68               0.0          0.0                0.0                    1  
46               0.0          0.0                0.0                    0  
82               0.0          0.0                0.0                    1  
115              0.0          0.0                0.0                    1  
85               0.0          0.0                0.0                    1  

[7 rows x 266 columns]

INTERSEZIONE NORMAL

In [58]:
intersection_Over_normal = set.intersection(intersection_Over,intersection_normal)
len(intersection_Over_normal)

0

INTERSEZIONE_MDS

In [64]:
intersection_Over_MDS = set.intersection(intersection_Over,intersection_normal)
len(intersection_Over_MDS)

0

INTERSEZIONE K BEST

In [65]:
intersection_Over_MDS = set.intersection(intersection_K,intersection_Over)
len(intersection_Over_MDS)

0

INTERSEZIONE UNDER + OVER 

In [68]:
intersection_Over_under = set.intersection(intersection_Random,intersection_Over)
len(intersection_Over_under)

7

In [69]:
df1.loc[intersection_Over_under]

vocal_channel  statement  repetition  sex       mean       q25       q50  \
99             1.0        1.0         0.0  0.0   0.787946 -0.115766 -0.020881   
67             1.0        0.0         0.0  1.0  -0.255898 -1.588189 -0.020881   
68             1.0        1.0         1.0  1.0   0.106668 -3.500140 -0.020881   
46             0.0        1.0         1.0  0.0   3.656416 -3.016658  8.690469   
82             1.0        1.0         1.0  0.0  -0.334822 -2.862823 -0.020881   
115            0.0        0.0         1.0  1.0  -1.973882 -4.071528  4.334794   
85             1.0        1.0         0.0  1.0 -14.355142 -1.588189 -8.732230   

          q75       kur      skew  ...  stft_skew_w4  emotion_angry  \
99  -0.267869  1.419436  3.260225  ...     -2.198188            0.0   
67   2.413698  1.065837  0.083170  ...     -1.359285            0.0   
68   4.283415  0.635975  0.113697  ...      2.276719            0.0   
46   2.118480 -0.750047  0.522037  ...     -1.770026            0.0   
82   1.847863 -0.460915  1.366414  ...      2.903386            0.0   
115  4.923055 -0.206086  0.404534  ...     -1.086900            1.0   
85   1.159020  3.611617  1.527304  ...     -2.211658            1.0   

     emotion_calm  emotion_disgust  emotion_fearful  emotion_happy  \
99            0.0              0.0              0.0            1.0   
67            0.0              0.0              0.0            0.0   
68            0.0              0.0              1.0            0.0   
46            0.0              0.0              1.0            0.0   
82            0.0              0.0              1.0            0.0   
115           0.0              0.0              0.0            0.0   
85            0.0              0.0              0.0            0.0   

     emotion_neutral  emotion_sad  emotion_surprised  emotional_intensity  
99               0.0          0.0                0.0                    1  
67               0.0          1.0                0.0                    1  
68               0.0          0.0                0.0                    1  
46               0.0          0.0                0.0                    0  
82               0.0          0.0                0.0                    1  
115              0.0          0.0                0.0                    1  
85               0.0          0.0                0.0                    1  

[7 rows x 266 columns]